CREATE DATABASE BD_VETERINARIA;
USE BD_VETERINARIA; 

----------------- TABLAS --------------------
CREATE TABLE TB_USUARIO(
	ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
	DNI_USUARIO VARCHAR(9) NOT NULL,
    NOMBRES_USUARIO VARCHAR(50) NOT NULL,
    APELLIDOS_USUARIO VARCHAR(50) NOT NULL,
    DIRECCION_USUARIO VARCHAR(50),
    CELULAR_USUARIO INT(9) NOT NULL,
    EMAIL_USUARIO VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD_USUARIO VARCHAR(50) NOT NULL, 
    ROL_USUARIO VARCHAR(14) NOT NULL
);

CREATE TABLE TB_MASCOTAS(
	ID_MASCOTA INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    NOMBRE_MASCOTA VARCHAR(30) NOT NULL,
    ESPECIE_MASCOTA VARCHAR(20) NOT NULL,
    SEXO_MASCOTA CHAR(1),
    RAZA_MASCOTA VARCHAR(50) NOT NULL,
    FECHA_NACIMIENTO_MASCOTA DATE,
    IMAGEN_MASCOTA BLOB NOT NULL,
    EVIDENCIA_MASCOTA BLOB NOT NULL,
    
    CONSTRAINT FK_USUARIO01 FOREIGN KEY(ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO) 
);

CREATE TABLE TB_CITAS(
	ID_CITA INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    FECHA_HORA_CITA DATETIME,
    MOTIVO_CITA VARCHAR(50),
    
	CONSTRAINT FK_USUARIO02 FOREIGN KEY(ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO) 
);

----------------- INSERCIÓN DE DATOS --------------------

INSERT INTO TB_USUARIO(DNI_USUARIO, NOMBRES_USUARIO, APELLIDOS_USUARIO, DIRECCION_USUARIO,CELULAR_USUARIO,
						EMAIL_USUARIO, PASSWORD_USUARIO, ROL_USUARIO)
VALUES('75632148', 'Alejandro Saul', 'Rojas Gamboa', 'Av. Arequipa 4563', 965823179, 'alejandrorojas@gmail.com', '1234', 'Cliente');
INSERT INTO TB_USUARIO(DNI_USUARIO, NOMBRES_USUARIO, APELLIDOS_USUARIO, DIRECCION_USUARIO,CELULAR_USUARIO,
						EMAIL_USUARIO, PASSWORD_USUARIO, ROL_USUARIO)
VALUES('735417658', 'Maria Alejandra', 'Clemente Malasquez', 'Av. Tacna 6354', 975621493, 'mariaalejandrac@gmail.com', '7894', 'Cliente');
INSERT INTO TB_USUARIO(DNI_USUARIO, NOMBRES_USUARIO, APELLIDOS_USUARIO, DIRECCION_USUARIO,CELULAR_USUARIO,
						EMAIL_USUARIO, PASSWORD_USUARIO, ROL_USUARIO)
VALUES('745612899', 'Camila Isabel', 'Dioses Ramos', 'Calle German Stiglich 4563', 963547819, 'camiladioses@gmail.com', '56Alos8', 'Cliente');
INSERT INTO TB_USUARIO(DNI_USUARIO, NOMBRES_USUARIO, APELLIDOS_USUARIO, DIRECCION_USUARIO,CELULAR_USUARIO,
						EMAIL_USUARIO, PASSWORD_USUARIO, ROL_USUARIO)
VALUES('78549657', 'Renzo Ricardo', 'Vasquez Perez', 'Calle C 10', 935689412, 'renzovasquez@gmail.com', 'REDU96547', 'Administrador');


INSERT INTO TB_MASCOTAS(ID_USUARIO,NOMBRE_MASCOTA, ESPECIE_MASCOTA, SEXO_MASCOTA, RAZA_MASCOTA, FECHA_NACIMIENTO_MASCOTA,
						IMAGEN_MASCOTA, EVIDENCIA_MASCOTA)
VALUES(1,'Zeus', 'Perro', 'M', 'Pitbull', '2022-10-03',
		'https://t1.uc.ltmcdn.com/es/posts/1/1/1/como_adiestrar_a_un_pitbull_34111_orig.jpg',
        'https://www.kivet.com/wp-content/uploads/2022/08/calendario_vacunacion_perro.webp'); 
INSERT INTO TB_MASCOTAS(ID_USUARIO,NOMBRE_MASCOTA, ESPECIE_MASCOTA, SEXO_MASCOTA, RAZA_MASCOTA, FECHA_NACIMIENTO_MASCOTA,
						IMAGEN_MASCOTA, EVIDENCIA_MASCOTA)
VALUES(2,'Copito', 'Conejo', 'F', 'MiniRex', '2023-01-22',
		'https://wakyma.com/blog/wp-content/uploads/2017/06/Te-lo-contamos-todo-sobre-el-conejo-mini-rex',
        'https://www.kivet.com/wp-content/uploads/2022/08/calendario_vacunacion_conejo.webp'); 
INSERT INTO TB_MASCOTAS(ID_USUARIO,NOMBRE_MASCOTA, ESPECIE_MASCOTA, SEXO_MASCOTA, RAZA_MASCOTA, FECHA_NACIMIENTO_MASCOTA,
						IMAGEN_MASCOTA, EVIDENCIA_MASCOTA)
VALUES(3,'Rose', 'Gato', 'F', 'Britanico de pelo corto', '2022-03-18',
		'https://smylepets.com/wp-content/uploads/2021/04/british-shorthair.jpg',
        'https://www.kivet.com/wp-content/uploads/2022/08/calendario_vacunacion_gato.webp'); 

----------------- VISTAS --------------------

CREATE view VW_DATOSCLIENTE
AS 
SELECT C.NOMBRES_USUARIO 'Nombres',
       C.APELLIDOS_USUARIO 'Apellidos',
       C.CELULAR_USUARIO 'Numero celular', 
       C.EMAIL_USUARIO 'Correo electronico'
FROM TB_USUARIO C 
WHERE ROL_USUARIO != 'Administrador';

----------------- TRIGGERS --------------------

CREATE TABLE TB_AUDITA_CITAS(
	ID_CITA INT,
    ID_USUARIO INT,
    FECHA_HORA_CITA DATETIME,
    MOTIVO_CITA VARCHAR(50),
    UPDATED_AT DATETIME NOT NULL,
    USUARIO VARCHAR(50) NOT NULL,
    OPERATION CHAR(3),
    CHECK(OPERATION ='INS' OR OPERATION = 'DEL' OR OPERATION = 'UPD')
);


DELIMITER //

CREATE TRIGGER TGR_INSERT_CITAS
AFTER INSERT ON TB_CITAS
FOR EACH ROW
BEGIN
    INSERT INTO TB_AUDITA_CITAS (
        ID_CITA,
        ID_USUARIO,
        FECHA_HORA_CITA,
        MOTIVO_CITA,
        UPDATED_AT,
        USUARIO,
        OPERATION
    )
    VALUES (
        NEW.ID_CITA,
        NEW.ID_USUARIO,
        NEW.FECHA_HORA_CITA,
        NEW.MOTIVO_CITA,
        NOW(),
        USER(),
        'INS'
    );
END //

DELIMITER ;


DELIMITER //

CREATE TRIGGER TGR_DELETE_CITAS
AFTER DELETE ON TB_CITAS
FOR EACH ROW
BEGIN
    INSERT INTO TB_AUDITA_CITAS (
        ID_CITA,
        ID_USUARIO,
        FECHA_HORA_CITA,
        MOTIVO_CITA,
        UPDATED_AT,
        USUARIO,
        OPERATION
    )
    VALUES (
        OLD.ID_CITA,
        OLD.ID_USUARIO,
        OLD.FECHA_HORA_CITA,
        OLD.MOTIVO_CITA,
        NOW(),
        USER(),
        'DEL'
    );
END //

DELIMITER ;


DELIMITER //

CREATE TRIGGER TGR_UPDATE_CITAS
AFTER UPDATE ON TB_CITAS
FOR EACH ROW
BEGIN
    INSERT INTO TB_AUDITA_CITAS (
        ID_CITA,
        ID_USUARIO,
        FECHA_HORA_CITA,
        MOTIVO_CITA,
        UPDATED_AT,
        USUARIO,
        OPERATION
    )
    VALUES (
        NEW.ID_CITA,
        NEW.ID_USUARIO,
        NEW.FECHA_HORA_CITA,
        NEW.MOTIVO_CITA,
        NOW(),
        USER(),
        'UPD'
    );
END //

DELIMITER ;



INSERT INTO TB_CITAS(ID_USUARIO, FECHA_HORA_CITA, MOTIVO_CITA)
VALUES(1, '2023-11-12 15:30:00', 'Chequeo anual');

INSERT INTO TB_CITAS(ID_USUARIO, FECHA_HORA_CITA, MOTIVO_CITA)
VALUES(2, '2023-11-12 13:30:00', 'Chequeo anual');


